# Generated by Django 5.0.2 on 2024-02-23 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField()),
                ('job_title', models.CharField(max_length=32)),
                ('employer', models.CharField(max_length=32)),
                ('notes', models.TextField()),
                ('followed_up', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('APL', 'Applied'), ('INT', 'Interview Booked'), ('SCS', 'SUCCESSFUL'), ('UNS', 'UNSUCCESSFUL')], default='APL', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='JobAPI.application')),
            ],
        ),
    ]
