# Generated by Django 5.0.2 on 2024-02-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAPI', '0002_application_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='location',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
