# Generated by Django 5.0.2 on 2024-02-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAPI', '0003_interview_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APL', 'Applied'), ('INT', 'Interview Booked'), ('SCS', 'Successful'), ('UNS', 'Unsuccessful')], default='APL', max_length=3),
        ),
    ]
