# Generated by Django 5.0.2 on 2024-03-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAPI', '0004_interview_notes_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
