# Generated by Django 5.0.2 on 2024-03-15 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobAPI', '0007_alter_application_date_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_applied',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
